print("Todays date: ")
curDate = input()
print("Breakfast calories: ")
bCal = int(input())
print("Lunch calories: ")
lCal = int(input())
print("Dinner calories: ")
dCal = int(input())
print("Calorie content for " + curDate + ": " + str(bCal + lCal + dCal))